# Generated by Django 5.0.6 on 2024-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('bn', 'Bangla')], null=True, verbose_name='Language'),
        ),
    ]
