# Generated by Django 5.0.6 on 2024-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
