# Generated by Django 5.0.6 on 2024-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
