# Generated by Django 5.0.6 on 2024-05-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useraccount_groups_useraccount_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_picture',
        ),
    ]
