# Generated by Django 5.0.6 on 2024-05-17 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favourite_topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, null=True, size=None),
        ),
    ]
