# Generated by Django 5.0.6 on 2024-05-17 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraccount_favourite_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favourite_topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None),
        ),
    ]
