# Generated by Django 5.0.6 on 2024-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
