# Generated by Django 5.0.6 on 2024-08-28 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_activeusercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeusercount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
