# Generated by Django 5.0.6 on 2024-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_activeusercount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeusercount',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
