# Generated by Django 5.0.6 on 2024-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0005_profile_personal_website_profile_profile_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
    ]
