# Generated by Django 5.0.6 on 2024-06-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_userinfo_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='division',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='state',
        ),
    ]
