# Generated by Django 5.0.6 on 2024-06-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_remove_userinfo_division_remove_userinfo_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='city',
            new_name='region',
        ),
    ]
