# Generated by Django 5.0.6 on 2024-07-17 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('predict', '0003_userreadrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreadrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userreadrecord',
            name='read_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userreadrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userreadrecord',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'read_count'), name='unique_user_post_read_count'),
        ),
    ]
