# Generated by Django 5.0.6 on 2024-07-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_alter_userreadrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreadrecord',
            name='read_count',
            field=models.PositiveIntegerField(),
        ),
    ]
