# Generated by Django 5.0.6 on 2024-07-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_alter_userreadrecord_read_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreadrecord',
            name='read_at',
        ),
    ]
