# Generated by Django 5.0.6 on 2024-07-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('link', models.URLField(unique=True, verbose_name='Link')),
                ('type', models.CharField(choices=[('web', 'Website'), ('yt', 'Youtube')], verbose_name='Type')),
            ],
        ),
    ]
