# Generated by Django 5.0.6 on 2024-07-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RssLinks',
            new_name='RssLink',
        ),
    ]
