# Generated by Django 5.0.6 on 2024-07-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsslink',
            name='base_link',
            field=models.URLField(blank=True, null=True, verbose_name='Base Link'),
        ),
    ]
