# Generated by Django 5.0.6 on 2024-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_rename_rsslinks_rsslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsslink',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('text', 'Text')], max_length=10, null=True),
        ),
    ]
