# Generated by Django 5.0.6 on 2024-07-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_rsslink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsslink',
            name='type',
            field=models.CharField(blank=True, choices=[('web', 'Website'), ('yt', 'YouTube')], max_length=10, null=True),
        ),
    ]
