# Generated by Django 5.0.6 on 2024-07-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_alter_rsslink_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RssLink',
        ),
    ]
